#!/usr/bin/env bash

SPECS = '../parameters/specs.txt'
nimages = "$(\grep NIMAGES $SPECS | cut -d= -f 2)"

grep -o '\-\([0-9]*\.\)\?[0-9]\+' 0-0/gaussian-1-data.xyz | head -n 1 >energies.txt
for i in $(seq 0 1 $((nimages - 1))); do
    count=$(ls -1 $i-$((i + 1))/*.log | wc -l)
    grep -o '\-\([0-9]*\.\)\?[0-9]\+' $i-$((i + 1))/gaussian-${count}-data.xyz | head -n 1 >>energies.txt
done
grep -o '\-\([0-9]*\.\)\?[0-9]\+' 0-$((nimages + 1))/gaussian-1-data.xyz | head -n 1 >>energies.txt
exit 0
